# Generated by Django 4.1 on 2022-08-10 20:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description_short', models.CharField(max_length=1024)),
                ('description_long', tinymce.models.HTMLField(blank=True)),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'unique_together': {('lng', 'lat')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('src', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Картинка')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['order'],
            },
        ),
    ]
