# Generated by Django 4.1 on 2022-08-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_src_image_path_alter_image_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='picture',
        ),
    ]
